document.writeln("        <header>");
document.writeln("            <nav>");
document.writeln("                <ul>");
document.writeln("                    <li><a href=\'index.html\'>首页</a></li>");
document.writeln("                    <li><a href=\'media.html\'>媒体</a></li>");
document.writeln("                    <li><a href=\'tools.html\'>工具</a></li>");
document.writeln("                    <li><a href=\'nav.html\'>导航</a></li>");
document.writeln("                    <li><a href=\'https://github.com/minus53K/minus53K.github.io\'>关于</a></li>");
document.writeln("                </ul>");
document.writeln("            </nav>");
document.writeln("        </header>");